Repository osu-tournament-rating/otr-docs, pull requests merged in 2024-09, with the labels that each got.

#7 Preliminary edits to algorithm documentation
  docs/otrd.tree
  docs/topics/Initial-Ratings.md
  docs/topics/Match-Cost.md
  docs/topics/Overview.md
  docs/topics/Rating-Calculation.md
  docs/topics/Rating-Decay.md
  docs/topics/Score-Modifications.md
  docs/topics/Tournament-Approval.md
Labels: documentation, size/L

#10 Shorten title
  docs/cfg/buildprofiles.xml
  docs/otr.tree
  docs/writerside.cfg
Labels: size/S

#20 Overhaul documentation
  docs/otr.tree
  docs/redirection-rules.xml
  docs/topics/API-Configuration.md
  docs/topics/API-Getting-Started.md
  docs/topics/Contribution-Guide.md
  docs/topics/Contributions.md
  docs/topics/Data.md
  docs/topics/Database-Setup-Backup-and-Recovery.md
  docs/topics/Database-Setup.md
  docs/topics/Development.md
  docs/topics/Disaster-Recovery.md
  docs/topics/Getting-Started.md
  docs/topics/Migrations.md
  docs/topics/Web-Getting-Started.md
  docs/topics/o-TR-API.md
  docs/topics/o-TR-Database.md
  docs/topics/o-TR-Docs.md
  docs/topics/o-TR-Processor.md
  docs/topics/o-TR-Web.md
Labels: size/XL
