Repository osu-tournament-rating/otr-docs, pull requests merged in 2025-04, with the labels that each got.

#52 Edits
  docs/topics/Sample-Match.md
Labels: size/M

#51 Create sample match calc documentation
  docs/topics/Sample-Match.md
Labels: documentation, size/L

#56 Obsidian restructure Merge
  About/Terms of Use.md
  Applications/API Clients/API Clients.md
  Applications/API/Code Quality.md
  Applications/API/Configuration.md
  Applications/API/Getting Started.md
  Applications/API/Overview.md
  Applications/API/Related Applications/DataWorkerService.md
  Applications/API/Terms of Use.md
  Applications/Database/Data.md
  Applications/Database/Disaster Recovery.md
  Applications/Database/Migrations.md
  Applications/Database/Setup.md
  Applications/Docs/Setup.md
  Applications/Processor/Getting Started.md
  Applications/Processor/Overview.md
  Applications/Web/Getting Started.md
  Contribute/Contribution Guide.md
  Rating Framework/Data Processing/Automated Checks.md
  Rating Framework/Data Processing/Data Processing Overview.md
  Rating Framework/Data Processing/Data Verification.md
  Rating Framework/Data Processing/Tournament Approval.md
  Rating Framework/Rating Calculation/Initial Ratings.md
  Rating Framework/Rating Calculation/Match Cost.md
  Rating Framework/Rating Calculation/Rating Calculation Overview.md
  Rating Framework/Rating Calculation/Rating Decay.md
  Rating Framework/Rating Calculation/Sample Match.md
  Rating Framework/Setup For Local Use.md
  docs/.DS_Store
  docs/topics/API Clients.md
  docs/topics/API Development.md
  docs/topics/API Related Services.md
  docs/topics/API.md
  docs/topics/Database.md
  docs/topics/Docs Contribution.md
  docs/topics/Docs Getting Started.md
  docs/topics/Docs.md
  docs/topics/Web.md
  images/co23-example.png
  images/completion_procedure.png
  images/completion_procedure_dark.png
  images/convert_table_to_xml.png
  images/convert_table_to_xml_dark.png
  images/new-oauth-app-fields.png
  images/new-oauth-app.png
  images/new_topic_options.png
  images/new_topic_options_dark.png
  images/sample-oauth-app.png
  images/tests_passing.png
  o!TR Docs.md
Labels: size/L

#57 Sidebar Cleanup
  About/Team.md
  About/Terms of Use.md
  Applications/API/Attachments/new-oauth-app-fields.png
  Applications/API/Attachments/new-oauth-app.png
  Applications/API/Attachments/sample-oauth-app.png
  Applications/API/Attachments/tests_passing.png
  Applications/API/Overview.md
  Applications/API/Terms of Use.md
  Applications/Database/Data.md
  Home.md
  Rating Framework/Data Processing/Attachements/co23-example.png
  Steps to get started.md
  images/completion_procedure.png
  images/completion_procedure_dark.png
  images/convert_table_to_xml.png
  images/convert_table_to_xml_dark.png
  images/new_topic_options.png
  images/new_topic_options_dark.png
Labels: size/L

#58 .env hotfix
  Applications/Web/Getting Started.md
Labels: size/M
