Repository osu-tournament-rating/otr-docs, pull requests merged in 2025-02, with the labels that each got.

#27 Update to .NET 9.0
  docs/topics/API-Getting-Started.md
Labels: size/XS

#30 Document automated checks under `o!TR/Data Processing/Automated Checks`
  docs/images/co23-example.png
  docs/otr.tree
  docs/topics/Automated-Checks.md
  docs/topics/Contributions.md
  docs/topics/DataWorkerService.md
  docs/topics/Development.md
  docs/topics/Overview.md
  docs/topics/Related-Services.md
  docs/topics/Score-Modifications.md
  docs/topics/o-TR-API.md
  docs/topics/o-TR-Database.md
  docs/topics/o-TR-Docs.md
  docs/topics/o-TR-Processor.md
  docs/topics/o-TR-Web.md
Labels: documentation, enhancement, size/L

#34 Fix broken flowchart blocks
  docs/topics/Automated-Checks.md
Labels: size/S

#35 Fix another parsing error
  docs/topics/Automated-Checks.md
Labels: size/XS

#36 Fix another more things
  docs/topics/Automated-Checks.md
Labels: size/XS

#37 Fixing broken link in otr web section
  docs/topics/o-TR-Web.md
Labels: size/XS
