Repository osu-tournament-rating/otr-docs, pull requests merged in 2025-03, with the labels that each got.

#45 Add docs for client gen
  docs/otr.tree
  docs/topics/Regenerate-Deploy.md
  docs/topics/o-TR-API-Clients.md
Labels: documentation, size/M

#42 Adding Tabs to account for OS differences with multiline commands + misc. changes
  docs/topics/API-Configuration.md
  docs/topics/Contact.md
  docs/topics/Database-Setup.md
  docs/topics/Disaster-Recovery.md
  docs/topics/Migrations.md
Labels: size/L

#46 Converts flowcharts into collapsible elements
  docs/topics/Automated-Checks.md
Labels: size/L

#47 Updating team/contact
  docs/topics/Contact.md
  docs/topics/Team.md
Labels: size/M

#49 Team Hotfix
  docs/topics/Team.md
Labels: size/XS
